//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerFinManaSys.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public System.Guid E_ID { get; set; }
        public System.Guid E_UID { get; set; }
        public System.Guid E_Type { get; set; }
        public decimal E_Amount { get; set; }
        public System.DateTime E_Date { get; set; }
        public string E_Remark { get; set; }
    }
}
