//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerFinManaSys.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public System.Guid I_ID { get; set; }
        public decimal I_Amount { get; set; }
        public System.DateTime I_Date { get; set; }
        public string I_Remark { get; set; }
        public System.Guid I_UID { get; set; }
    }
}
