//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerFinManaSys.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public System.Guid L_ID { get; set; }
        public System.Guid L_UID { get; set; }
        public string L_HostName { get; set; }
        public string L_IP { get; set; }
        public string L_City { get; set; }
        public System.DateTime L_LoginTime { get; set; }
        public int L_Role { get; set; }
    }
}
