//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerFinManaSys.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public System.Guid U_ID { get; set; }
        public string U_Name { get; set; }
        public string U_PassWord { get; set; }
        public int U_Role { get; set; }
        public string U_Tel { get; set; }
        public System.DateTime U_RegistDate { get; set; }
        public Nullable<System.DateTime> U_LastLoginTime { get; set; }
    }
}
